### ISSUE TITLE
Скрипт для поиска необновленных ссылок

### ISSUE THREAD

**Issue by alexander-naumov** [openbsd-ru/openbsd-ru.github.io#12]
Снова скрипт для поиска ссылок :) Но на этот раз необновленных. Под необновленными ссылками я подразумеваю _родные_ ссылки, ведущие на страницы с openbsd.org и прочие.
Скрипт должен найти все ссылки с наших страниц, но показать лишь необновленные, для которых у нас уже есть перевод.

К примеру, на странице A есть ссылка на openbsd.org/security.html. У нас уже есть перевод security.html, значит эту ссылку надо обновить. Скрипт толжен показывать на какой странице находится родная ссылка (страница A) и на какую именно родную страницу она ведет (openbsd.org/security.html).

**Comment by app** [comment]
Вот такое решение подойдет?
https://gist.github.com/app/28001510028570e7a76bba9740641f84
Выдает строки вида
`./faq/faq1.html:127:  <li><a href="https://www.openbsd.org/arm64.html"    >arm64</a>`
Где файл с номером строки - это место ссылки, требующей обновления.
Ссылка - это то что нужно заменить на уже имеющийся перевод.

**Comment by alexander-naumov** [comment]
> Вот такое решение подойдет?
> https://gist.github.com/app/28001510028570e7a76bba9740641f84

Это именно то, что нужно! Я сейчас протестировал - работает отлично ;-)
Я добавлю на днях этот скрипт к travis.

Большое спасибо, Андрей
(Я добавлю в скрипт авторство aka copyright).
