### ISSUE TITLE
Формулировка

### ISSUE THREAD

**Issue by ssh3** [openbsd-ru/openbsd-ru.github.io#22]
В https://openbsd-ru.github.io/faq/faq4.html смущает следующее изложение:

> Полная установка OpenBSD состоит из нескольких компонент.
> Вот краткое их описание:

В оригинале:
> The complete OpenBSD installation is broken up into a number of file sets:

Предлагаю привести к виду:
> Полная инсталляция OpenBSD разбита на несколько установочных компонент.

Понятно, что термин [инсталляция](http://gramota.ru/slovari/dic/?word=%D0%B8%D0%BD%D1%81%D1%82%D0%B0%D0%BB%D0%BB%D1%8F%D1%86%D0%B8%D1%8F&all=x) заимствованный, но использовав его мы можем использовать ранее введенный в обиход термин "[установочные компоненты](https://openbsd-ru.github.io/faq/faq4.html#Download)".

**Comment by alexander-naumov** [comment]
Согласен. Спасибо за замечание.
