### ISSUE TITLE
Сломанные ссылки на сайте (404)

### ISSUE THREAD

**Issue by ligurio** [openbsd-ru/openbsd-ru.github.io#3]
собрал с помощью wget все сломанные ссылки на сайте:

```
$ wget -o openbsd-ru.log -r -l 10 --spider https://openbsd-ru.github.io/
$ grep -B4 'broken link!' openbsd-ru.log | grep "https://openbsd-ru.github.io"
```
[x] https://openbsd-ru.github.io/favicon.ico
https://openbsd-ru.github.io/64.html
https://openbsd-ru.github.io/anoncvs.html
https://openbsd-ru.github.io/policy.html
https://openbsd-ru.github.io/plat.html
https://openbsd-ru.github.io/donations.html
https://openbsd-ru.github.io/innovations.html
https://openbsd-ru.github.io/mail.html
[x] https://openbsd-ru.github.io/advisories/pgpkey.txt
https://openbsd-ru.github.io/papers/index.html
https://openbsd-ru.github.io/faq/faq5.html
https://openbsd-ru.github.io/faq/faq10.html
https://openbsd-ru.github.io/faq/ports/index.html
https://openbsd-ru.github.io/faq/upgrade64.html
https://openbsd-ru.github.io/faq/ports/testing.html
https://openbsd-ru.github.io/faq/current.html
https://openbsd-ru.github.io/report.html
https://openbsd-ru.github.io/faq/pf/index.html
https://openbsd-ru.github.io/faq/faq1.html
https://openbsd-ru.github.io/faq/faq4.html
https://openbsd-ru.github.io/faq/faq15.html
https://openbsd-ru.github.io/faq/faq14.html
https://openbsd-ru.github.io/faq/faq6.html
https://openbsd-ru.github.io/faq/faq7.html
https://openbsd-ru.github.io/faq/faq8.html
https://openbsd-ru.github.io/faq/faq11.html
https://openbsd-ru.github.io/faq/faq13.html
https://openbsd-ru.github.io/faq/faq17.html
https://openbsd-ru.github.io/faq/pf/config.html
https://openbsd-ru.github.io/faq/pf/macros.html
https://openbsd-ru.github.io/faq/pf/tables.html
https://openbsd-ru.github.io/faq/pf/filter.html
https://openbsd-ru.github.io/faq/pf/nat.html
https://openbsd-ru.github.io/faq/pf/rdr.html
https://openbsd-ru.github.io/faq/pf/shortcuts.html
https://openbsd-ru.github.io/faq/pf/options.html
https://openbsd-ru.github.io/faq/pf/anchors.html
https://openbsd-ru.github.io/faq/pf/pools.html
https://openbsd-ru.github.io/faq/pf/tagging.html
https://openbsd-ru.github.io/faq/pf/logging.html
https://openbsd-ru.github.io/faq/pf/perf.html
https://openbsd-ru.github.io/faq/pf/ftp.html
https://openbsd-ru.github.io/faq/pf/authpf.html
https://openbsd-ru.github.io/faq/pf/carp.html
https://openbsd-ru.github.io/faq/pf/example1.html
[x] https://openbsd-ru.github.io/openssh/favicon.ico
[x] https://openbsd-ru.github.io/openssh/txt/release-7.9
[x] https://openbsd-ru.github.io/openssh/openbsd.css
[x] https://openbsd-ru.github.io/openssh/txt/release-7.6
https://openbsd-ru.github.io/openssh/legacy.html
[x] https://openbsd-ru.github.io/openssh/txt/socks4.protocol
[x] https://openbsd-ru.github.io/openssh/txt/socks4a.protocol
[x] https://openbsd-ru.github.io/openssh/txt/draft-ietf-secsh-filexfer-02.txt
[x] https://openbsd-ru.github.io/openssh/txt/draft-ietf-secsh-publickeyfile-02.txt
[x] https://openbsd-ru.github.io/openssh/txt/draft-miller-secsh-compression-delayed-00.txt
[x] https://openbsd-ru.github.io/openssh/txt/draft-miller-secsh-umac-01.txt
https://openbsd-ru.github.io/openssh/openbsd.html
https://openbsd-ru.github.io/openssh/portable.html

**Comment by alexander-naumov** [comment]
Сергей, спасибо за список.

Да, эти страницы надо перевести в первую очередь; либо переписать некоторые из них так, чтобы они указывали на оригинал.
Было бы здорово еще видеть, с каких страниц какие именно ссылки поломаны.

**Comment by alexander-naumov** [comment]
Основные поломанные ссылки были с faq/index.html
Они исправленны.

Вот список того, что еще еще надо будет отловить. 18 штук:

--2019-04-01 22:56:46--  https://openbsd-ru.github.io/64.html
--2019-04-01 22:56:48--  https://openbsd-ru.github.io/policy.html
--2019-04-01 22:56:48--  https://openbsd-ru.github.io/plat.html
--2019-04-01 22:56:48--  https://openbsd-ru.github.io/donations.html
--2019-04-01 22:56:49--  https://openbsd-ru.github.io/innovations.html
--2019-04-01 22:56:49--  https://openbsd-ru.github.io/mail.html
--2019-04-01 22:56:49--  https://openbsd-ru.github.io/papers/index.html
--2019-04-01 22:56:49--  https://openbsd-ru.github.io/faq/faq10.html
--2019-04-01 22:56:49--  https://openbsd-ru.github.io/faq/ports
--2019-04-01 22:56:50--  https://openbsd-ru.github.io/stable.html
--2019-04-01 22:56:50--  https://openbsd-ru.github.io/ftp.html
--2019-04-01 22:56:50--  https://openbsd-ru.github.io/faq/faq5.html
--2019-04-01 22:56:50--  https://openbsd-ru.github.io/errata.html
--2019-04-01 22:56:50--  https://openbsd-ru.github.io/anoncvs.shar
--2019-04-01 22:57:18--  https://openbsd-ru.github.io/faq/faq6.html
--2019-04-01 22:57:18--  https://openbsd-ru.github.io/openssh/legacy.html
--2019-04-01 22:57:18--  https://openbsd-ru.github.io/openssh/openbsd.html
--2019-04-01 22:57:18--  https://openbsd-ru.github.io/openssh/portable.html

**Comment by oleg-pahl** [comment]
https://openbsd-ru.github.io/faq/faq17.html - OK - Updated as Pull Request!

**Comment by alexander-naumov** [comment]
Добавил скрипт, который привязал к travis (он будет перезапускать скрипт после каждого нового коммита в этот репозиторий).
Скрипт показывает отсутствующую у нас в репозитории html-страницу, а так же страницы, где есть ссылки на неё.

Теперь, если кому лениво заниматься переводом, можно заняться отлавливанием поломаных ссылок. Раньше это тоже было возможно, но теперь это на много удобнее ;-)
