### ISSUE TITLE
Проблема с unwind и вайфаем решена.

### ISSUE THREAD

**Issue by artsi0m** [openbsd-ru/openbsd-ru.github.io#35]
По следам дискуссии в чате:
https://t.me/openbsd_ru/64238
- 
https://t.me/openbsd_ru/64246
https://t.me/openbsd_ru/64263
И отдельной статьи разработчика:
https://sha256.net/dynamic_host_configuration_please.html

Могу предложить два бранча на выбор:
Где целиком удалено:
https://github.com/artsi0m/openbsd-ru.github.io/tree/unwind-issue-delete
И где отредактировано:
https://github.com/artsi0m/openbsd-ru.github.io/tree/unwind-issue-rewrite

**Comment by alexander-naumov** [comment]
Я думаю, первый вариант лучше.

**Comment by alexander-naumov** [comment]
Пост добавлен в оглавление: https://github.com/openbsd-ru/openbsd-ru.github.io/commit/8d36d5d5e0e7fd65e1760558de5afca6415fd47f
Спасибо
