### ISSUE TITLE
fix links in faq index

### ISSUE THREAD

**Issue by elderone** [openbsd-ru/openbsd-ru.github.io#7]
В индексе FAQ все ссылки ведут на openbsd.org
https://github.com/openbsd-ru/openbsd-ru.github.io/blob/master/faq/index.html

**Comment by alexander-naumov** [comment]
Ну почему же все. Не все ;-)
15, 11 и 16 уже ведут на переведенные главы.
Пару дней назад @oleg-pahl добавил 17 главу, ее надо слинковать, да. Остальное пока не переведено.

**Comment by elderone** [comment]
Действительно :-)
