### ISSUE TITLE
Скрипт для сравнения версий

### ISSUE THREAD

**Issue by alexander-naumov** [openbsd-ru/openbsd-ru.github.io#8]
Нужен скрипт (желательно на python), который сравнивал бы версии переведенных страниц с их версиями в CVS.

Версии оригинальных страниц через web можно посмотреть тут: https://cvsweb.openbsd.org/www/
Или, к примеру, если есть локальный www-репозиторий, можно сделать
`cvs status FILENAME | grep Repository`

Версии переведенных страниц можно посмотреть через `git log FILENAME`

**Comment by oleg-pahl** [comment]
Hi,

Сегодня добавил FAQ Checker Shell Script : 
commit : dbf10c0b22698e3c7c659de3dcb2f1233cff4fa0
Посмотри, если все ровно -> можем закрыть Issue #8

BR
Oleg Pahl

**Comment by alexander-naumov** [comment]
Скрипт мне понравился, спасибо, но он он должен без проблем работать не только в OpenBSD, но и хотя бы в GNU системах (не у всех опенок на работе).

**Comment by alexander-naumov** [comment]
> 
> Usage:
> 
> ```
> $ cd faq
> $ chmod +x checher
> $ ./checher
> ```
 
Не совсем понятно зачем заходить в faq... Скрипт должен быть запущен из корня, рекурсивно пройтись по всем html и показать их версии. Сейчас он работает только для faq, и прежде чем закрыть эту issue хотелось бы конечно иметь возможность за раз проверять весь наш репозиторий. Сейчас запуск из корня выглядит так:

![checker-openbsd](https://user-images.githubusercontent.com/1872982/56950450-cf7c9d80-6b35-11e9-9043-4c16eb89d6bf.png)

p.s. в отчистке экрана нет никакой необходимости.

**Comment by oleg-pahl** [comment]
Запуск этого скрипта надо проводить из папки faq! В корне есть ru-community которую скрипт не должен трогать. могут появится и другие вложенные папки. но faq он пробивает на ура. требует доработки.

**Comment by alexander-naumov** [comment]
> В корне есть ru-community которую скрипт не должен трогать.

Да, ее надо пропускать. Все остальное, например, openssh или faq/pf или faq/ports/ скрипт должен проверять.

**Comment by alexander-naumov** [comment]
Добавил только что новый shell-скрипт. Он проверяет весь репозиторий, а не только faq. Есть возможность проверять только конкретные каталоги, что очень удобно. Каталог ru-community естественно пропускается.

Протестировал в openSUSE и OpenBSD 6.4.

Дальнейшие изменения в этот скрипт вносите пожалуйста только через pull request.
